language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
matrix:
  include:
    - python: "3.7"
      dist: xenial
install:
  - pip install -r requirements.txt
  - pip install -e .
  - craft install
script: python -m pytest
