from setuptools import setup, find_packages

setup(
    name=':package_name',
    version='0.0.1',
    package_dir={'': 'src'},
    description=':package_description',
    long_description=open("README.md", "r", encoding="utf-8").read(),
    url='https://github.com/hellomasonite/:package_name',
    author=':author_name',
    author_email=':author_email',
    license='MIT',
    include_package_data=True,
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'Topic :: Software Development :: Build Tools',
        'Environment :: Web Environment',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
        'Programming Language :: Python :: 3.5',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Topic :: Internet :: WWW/HTTP',
        'Topic :: Internet :: WWW/HTTP :: Dynamic Content',
        'Topic :: Internet :: WWW/HTTP :: WSGI',
        'Topic :: Software Development :: Libraries :: Application Frameworks',
        'Topic :: Software Development :: Libraries :: Python Modules',
    ],
    keywords=':package_keywords',
    packages=find_packages('src'),
    install_requires=[
    ],
    setup_requires=['wheel'],
    extras_require={
        'test': ['coverage', 'pytest'],
    },
    long_description_content_type='text/markdown',
)
